const enum REDUCER_ACTION_TYPE {
  ADD_CITY = "ADD_CITY",
  EDIT_CITY = "EDIT_CITY",
  DELETE_CITY = "DELETE_CITY",
  EDIT_PROVINCE = "EDIT_PROVINCE",
  SET_PROVINCE_SELECTED_ID = "SET_PROVINCE_SELECTED_ID",
  SET_CITY_SELECTED_ID = "SET_CITY_SELECTED_ID",
  GET_PROVINCE = "GET_PROVINCE",
  GET_CITY = "GET_CITY",
  SEARCH_FILTER = "SEARCH_FILTER",
}
export default REDUCER_ACTION_TYPE;
